(function(){
'use strict';
const A=window.StudyApp,C=window.StudyCore,$=id=>document.getElementById(id),uuid=()=>crypto.randomUUID(),now=()=>new Date().toISOString(),today=()=>C.dateKey(new Date());
let planEdit=null,eventEdit=null,limit=24,timer=A.getReviewTimer(),notificationKey='';
const dateText=date=>new Date(date+'T12:00:00').toLocaleDateString('pt-BR');
const emptyTimer=()=>({subject:'',topic:'',reviewId:'',startedAt:null,segments:[],mode:'idle'});
if(!timer||!Array.isArray(timer.segments))timer=emptyTimer();
function message(text,error=false){$('reviews-message').textContent=text;$('reviews-message').hidden=false;$('reviews-message').classList.toggle('error',error)}
function entities(){const d=A.snapshot();return {...d,plans:d.reviewPlans.filter(p=>!p.deleted),events:d.reviews.filter(r=>!r.deleted&&d.reviewPlans.some(p=>p.id===r.planId&&!p.deleted))}}
function commit(doc){A.commitReviews(doc.reviewPlans,doc.reviews)}
function subjectOptions(id,names,placeholder=null){const el=$(id),value=el.value;el.innerHTML=(placeholder===null?'':`<option value="">${placeholder}</option>`)+names.map(n=>`<option value="${esc(n)}">${esc(n)}</option>`).join('');if(names.includes(value))el.value=value;else if(placeholder!==null)el.value=''}
function subjects(){const d=entities(),names=[...new Set([...state.subjects.filter(s=>s.name.trim()).map(s=>s.name),...d.plans.map(p=>p.subject)])];for(const id of ['review-plan-subject','review-bulk-subject','review-timer-subject'])subjectOptions(id,names);subjectOptions('review-filter-subject',names,'Todas');if(timer.mode!=='idle')$('review-timer-subject').value=timer.subject}
function tasks(){const d=entities(),subject=$('review-timer-subject').value,prior=$('review-timer-task').value,pending=d.events.filter(r=>r.subject===subject&&r.status==='scheduled').sort((a,b)=>a.dueDate.localeCompare(b.dueDate));$('review-timer-task').innerHTML='<option value="">Revisão livre</option>'+pending.map(r=>`<option value="${esc(r.id)}">${esc(r.topic)} · ${dateText(r.dueDate)} · D+${r.interval}</option>`).join('');if(timer.mode!=='idle'){$('review-timer-task').value=timer.reviewId;$('review-timer-topic').value=timer.topic}else if(pending.some(r=>r.id===prior))$('review-timer-task').value=prior}
function timerMs(){return timer.segments.reduce((n,s)=>n+Math.max(0,s.end-s.start),0)+(timer.startedAt?Math.max(0,Date.now()-timer.startedAt):0)}
function persistTimer(){A.saveReviewTimer(timer)}
function paintTimer(){$('review-clock').textContent=C.formatClock(timerMs());$('review-timer-state').textContent=timer.mode==='running'?'Revisão em andamento':timer.mode==='paused'?'Pausada · o tempo não está contando':timer.mode==='stopped'?'Parada · salve para registrar as horas':'Pronto para iniciar';$('review-start').disabled=timer.mode==='running'||!$('review-timer-subject').value;$('review-start').textContent=timer.mode==='idle'?'Iniciar':'Retomar';$('review-pause').disabled=timer.mode!=='running';$('review-stop').disabled=timer.mode==='idle'||timer.mode==='stopped';$('review-save').disabled=timer.mode==='running'||timerMs()<1000;for(const id of ['review-timer-subject','review-timer-topic','review-timer-task'])$(id).disabled=timer.mode!=='idle'}
function pause(mode='paused'){if(timer.startedAt){timer.segments.push({start:timer.startedAt,end:Date.now()});timer.startedAt=null}timer.mode=mode;persistTimer();paintTimer()}
function start(){if(timer.mode==='idle'){timer.subject=$('review-timer-subject').value;timer.topic=$('review-timer-topic').value.trim();timer.reviewId=$('review-timer-task').value}if(!timer.subject||!timer.topic){message('Selecione a matéria e preencha o assunto da revisão.',true);return}A.pauseStudies();timer.startedAt=Date.now();timer.mode='running';persistTimer();paintTimer()}
$('review-start').onclick=start;$('review-pause').onclick=()=>pause();$('review-stop').onclick=()=>pause('stopped');
$('review-save').onclick=()=>{if(timer.mode==='running'||timerMs()<1000)return;const at=now(),group=uuid(),rows=C.splitSegments(timer.segments).map(part=>({id:uuid(),group,subject:timer.subject,topic:timer.topic,kind:'review',reviewId:timer.reviewId,...part,source:'timer',note:'',createdAt:at,updatedAt:at,deleted:false}));if(!rows.length)return;const reviewId=timer.reviewId;timer=emptyTimer();persistTimer();A.saveReviewSessions(rows,reviewId);$('review-timer-topic').value='';$('review-timer-task').value='';render();message(reviewId?'Revisão finalizada e horas registradas no histórico.':'Horas de revisão registradas no histórico.')};
$('review-timer-subject').onchange=()=>{if(timer.mode==='idle'){$('review-timer-task').value='';tasks();paintTimer()}};
$('review-timer-task').onchange=()=>{const event=entities().events.find(r=>r.id===$('review-timer-task').value);if(event)$('review-timer-topic').value=event.topic};
window.addEventListener('timerstart',e=>{if(e.detail.kind==='study'&&timer.mode==='running'){pause();message('O cronômetro de revisão foi pausado para iniciar o estudo.')}});
setInterval(()=>{if(timer.mode==='running')paintTimer()},500);
document.addEventListener('visibilitychange',()=>{persistTimer();paintTimer()});
window.addEventListener('pagehide',persistTimer);

function resetPlan(){planEdit=null;$('review-plan-heading').textContent='Registrar assunto estudado';$('review-plan-submit').textContent='Criar revisões';$('review-plan-cancel').hidden=true;$('review-plan-form').reset();$('review-plan-date').value=today()}
$('review-plan-cancel').onclick=resetPlan;
$('review-plan-form').onsubmit=e=>{e.preventDefault();const subject=$('review-plan-subject').value,topic=$('review-plan-topic').value.trim(),date=$('review-plan-date').value,notes=$('review-plan-notes').value.trim();if(!subject||!topic||!C.validDate(date)){message('Preencha matéria, assunto e uma data válida.',true);return}let d=A.snapshot();const existing=d.reviewPlans.find(p=>p.id===planEdit&&!p.deleted);if(existing){existing.subject=subject;existing.topic=topic;existing.studiedOn=date;existing.notes=notes;existing.updatedAt=A.timeStamp(existing.updatedAt);for(const r of d.reviews.filter(r=>r.planId===existing.id&&!r.deleted&&r.status==='scheduled')){r.subject=subject;r.topic=topic;r.dueDate=C.shiftAllowed(date,r.interval);r.updatedAt=A.timeStamp(r.updatedAt)}commit(d);message('Plano alterado. As revisões pendentes foram recalculadas; as finalizadas foram preservadas.')}else{const at=now(),bundle=C.buildReviews(subject,topic,date,notes,uuid(),at,uuid);d.reviewPlans.push(bundle.plan);d.reviews.push(...bundle.reviews);commit(d);message('Seis revisões agendadas. As datas de domingo foram ajustadas para segunda-feira.')}resetPlan();render()};
function renderAgenda(d){const subject=$('review-filter-subject').value,status=$('review-filter-status').value,query=$('review-filter-search').value.toLocaleLowerCase('pt-BR'),date=today();const records=d.events.filter(r=>(!subject||r.subject===subject)&&(!status||C.reviewState(r,date)===status)&&(!query||r.topic.toLocaleLowerCase('pt-BR').includes(query))).sort((a,b)=>{const order={overdue:0,scheduled:1,finished:2},sa=C.reviewState(a,date),sb=C.reviewState(b,date);return order[sa]-order[sb]||(sa==='finished'?C.stamp(b.doneAt)-C.stamp(a.doneAt):a.dueDate.localeCompare(b.dueDate))||a.subject.localeCompare(b.subject)});
$('review-list').innerHTML=records.slice(0,limit).map(r=>{const status=C.reviewState(r,date),plan=d.plans.find(p=>p.id===r.planId),label=status==='overdue'?'Vencida':status==='finished'?'Finalizada':r.dueDate===date?'Agendada · hoje':'Agendada';return `<article class="review-row ${status}" style="--subject-color:${C.subjectColor(r.subject)}"><div class="review-row-heading"><span class="subject-label">${esc(r.subject)}</span><span class="review-status ${status}">${label}</span></div><h3>${esc(r.topic)}</h3><p class="review-date">${dateText(r.dueDate)} <span>· D+${r.interval}</span>${r.doneAt?` · concluída em ${dateText(C.dateKey(new Date(r.doneAt)))}`:''}</p>${plan?.notes||r.notes?`<details class="review-notes"><summary>Observações</summary>${plan?.notes?`<p>${esc(plan.notes)}</p>`:''}${r.notes?`<p>${esc(r.notes)}</p>`:''}</details>`:''}<div class="review-actions">${status==='finished'?`<button type="button" data-reopen="${esc(r.id)}">Reabrir</button>`:`<button type="button" class="primary" data-timer="${esc(r.id)}">Revisar</button><button type="button" data-done="${esc(r.id)}">Finalizar sem cronômetro</button>`}<button type="button" data-edit="${esc(r.id)}">Editar data / notas</button><button type="button" class="danger-link" data-delete="${esc(r.id)}">Excluir</button></div></article>`}).join('')||'<p class="chart-empty">Nenhuma revisão com estes filtros. Registre um assunto para criar seu primeiro plano.</p>';$('review-more').hidden=records.length<=limit}
function renderPlans(d){const subject=$('review-filter-subject').value,query=$('review-filter-search').value.toLocaleLowerCase('pt-BR');const plans=d.plans.filter(p=>(!subject||p.subject===subject)&&(!query||p.topic.toLocaleLowerCase('pt-BR').includes(query))).sort((a,b)=>b.studiedOn.localeCompare(a.studiedOn));$('review-plans').innerHTML=plans.map(p=>{const events=d.events.filter(r=>r.planId===p.id),pending=events.filter(r=>r.status==='scheduled').length;return `<article class="plan-row" style="--subject-color:${C.subjectColor(p.subject)}"><div><span class="subject-label">${esc(p.subject)}</span><h3>${esc(p.topic)}</h3><p class="hint">Estudado em ${dateText(p.studiedOn)} · ${pending} pendente(s) · ${events.filter(r=>r.status==='done').length} finalizada(s)</p></div><div class="review-actions"><button type="button" data-plan-edit="${esc(p.id)}">Editar plano</button><button type="button" class="danger-link" data-plan-delete="${esc(p.id)}">Excluir plano</button></div></article>`}).join('')||'<p class="hint">Nenhum plano registrado.</p>'}
function updateReminders(d){const date=today(),due=d.events.filter(r=>r.status==='scheduled'&&r.dueDate<=date),overdue=due.filter(r=>r.dueDate<date).length,current=due.length-overdue,next=d.events.filter(r=>r.status==='scheduled'&&r.dueDate>date&&r.dueDate<=C.shiftAllowed(date,7)).length;$('reviews-overdue').textContent=overdue;$('reviews-today').textContent=current;$('reviews-next').textContent=next;$('reviews-finished').textContent=d.events.filter(r=>r.status==='done').length;$('review-reminder').hidden=!due.length;$('review-reminder-count').textContent=`${overdue} revisão(ões) vencida(s) e ${current} para hoje`;
let enabled=false;try{enabled=localStorage.getItem('ciclo-revisoes-notificar')==='true'}catch{}const key=date+':'+due.length;if(enabled&&due.length&&'Notification' in window&&Notification.permission==='granted'&&notificationKey!==key){notificationKey=key;try{new Notification('Ciclo de estudos · revisões',{body:`${overdue} vencida(s) e ${current} para hoje. Abra a agenda para revisar.`,tag:'ciclo-revisoes',icon:'diagram.png'})}catch{}}
}
function render(){subjects();tasks();paintTimer();const d=entities();renderAgenda(d);renderPlans(d);updateReminders(d)}
function eventUpdate(id,action){const d=A.snapshot(),r=d.reviews.find(r=>r.id===id&&!r.deleted);if(!r)return;if(action==='done'){r.status='done';r.doneAt=now();message('Revisão finalizada. Não foram lançadas horas; registre-as manualmente se necessário.')}if(action==='reopen'){r.status='scheduled';r.doneAt=null}if(action==='delete'){if(!confirm('Excluir esta revisão da agenda? As horas registradas no histórico continuarão preservadas.'))return;r.deleted=true}r.updatedAt=A.timeStamp(r.updatedAt);commit(d)}
$('review-list').onclick=e=>{const button=e.target.closest('button');if(!button)return;const ds=button.dataset,id=ds.timer||ds.done||ds.edit||ds.delete||ds.reopen,event=entities().events.find(r=>r.id===id);if(!event)return;if(ds.timer){if(timer.mode!=='idle'){message('Salve a sessão de revisão atual antes de iniciar outra.',true);$('review-clock').scrollIntoView({behavior:'smooth'});return}$('review-timer-subject').value=event.subject;tasks();$('review-timer-task').value=event.id;$('review-timer-topic').value=event.topic;start();$('review-clock').scrollIntoView({behavior:'smooth',block:'center'});return}if(ds.edit){eventEdit=id;$('review-edit-panel').hidden=false;$('review-edit-date').value=event.dueDate;$('review-edit-notes').value=event.notes||'';$('review-edit-panel').scrollIntoView({behavior:'smooth',block:'center'});return}eventUpdate(id,ds.done?'done':ds.reopen?'reopen':'delete')};
$('review-edit-cancel').onclick=()=>{eventEdit=null;$('review-edit-panel').hidden=true};
$('review-edit-form').onsubmit=e=>{e.preventDefault();const date=$('review-edit-date').value;if(!C.validDate(date))return;const d=A.snapshot(),r=d.reviews.find(r=>r.id===eventEdit&&!r.deleted);if(!r){message('Esta revisão foi excluída. Atualize a agenda.',true);return}r.dueDate=C.shiftAllowed(date);r.notes=$('review-edit-notes').value.trim();r.updatedAt=A.timeStamp(r.updatedAt);commit(d);$('review-edit-panel').hidden=true;eventEdit=null;message('Revisão alterada. A data foi ajustada para segunda-feira se caía no domingo.')};
$('review-plans').onclick=e=>{const button=e.target.closest('button');if(!button)return;const id=button.dataset.planEdit||button.dataset.planDelete,d=A.snapshot(),plan=d.reviewPlans.find(p=>p.id===id&&!p.deleted);if(!plan)return;if(button.dataset.planDelete){if(!confirm(`Excluir o plano completo de ${plan.topic}? Todas as revisões desse plano sairão da agenda; o histórico de horas ficará preservado.`))return;plan.deleted=true;plan.updatedAt=A.timeStamp(plan.updatedAt);for(const r of d.reviews.filter(r=>r.planId===id)){r.deleted=true;r.updatedAt=A.timeStamp(r.updatedAt)}commit(d);return}planEdit=id;$('review-plan-heading').textContent='Editar plano de revisões';$('review-plan-submit').textContent='Salvar plano';$('review-plan-cancel').hidden=false;$('review-plan-subject').value=plan.subject;$('review-plan-topic').value=plan.topic;$('review-plan-date').value=plan.studiedOn;$('review-plan-notes').value=plan.notes;$('review-plan-form').scrollIntoView({behavior:'smooth',block:'center'})};
$('review-bulk-shift').onclick=()=>{const subject=$('review-bulk-subject').value,delta=Number($('review-bulk-days').value);if(!Number.isInteger(delta)||Math.abs(delta)>365){message('Informe um deslocamento inteiro de até 365 dias.',true);return}const d=A.snapshot(),rows=d.reviews.filter(r=>r.subject===subject&&!r.deleted&&r.status==='scheduled');if(!rows.length){message('Esta matéria não tem revisões pendentes.');return}if(!confirm(`Deslocar ${rows.length} revisão(ões) de ${subject} em ${delta} dia(s)?`))return;for(const r of rows){r.dueDate=C.shiftAllowed(r.dueDate,delta);r.updatedAt=A.timeStamp(r.updatedAt)}commit(d);message('Datas pendentes alteradas. As revisões finalizadas não foram modificadas.')};
$('review-bulk-delete').onclick=()=>{const subject=$('review-bulk-subject').value,d=A.snapshot(),rows=d.reviews.filter(r=>r.subject===subject&&!r.deleted&&r.status==='scheduled');if(!rows.length){message('Esta matéria não tem revisões pendentes.');return}if(!confirm(`Excluir ${rows.length} revisão(ões) pendente(s) de ${subject}? As finalizadas e as horas realizadas ficarão preservadas.`))return;for(const r of rows){r.deleted=true;r.updatedAt=A.timeStamp(r.updatedAt)}for(const p of d.reviewPlans.filter(p=>p.subject===subject&&!p.deleted)){p.closed=true;p.updatedAt=A.timeStamp(p.updatedAt)}commit(d);message('Revisões pendentes excluídas. O histórico de horas foi preservado.')};
for(const id of ['review-filter-subject','review-filter-status'])$(id).onchange=()=>{limit=24;render()};$('review-filter-search').oninput=()=>{limit=24;const d=entities();renderAgenda(d);renderPlans(d)};$('review-more').onclick=()=>{limit+=24;render()};
$('review-reminder-open').onclick=()=>document.querySelector('[data-view="reviews-view"]').click();
$('review-notifications').onclick=async()=>{if(!('Notification' in window)){message('Este navegador não oferece notificações. Use o arquivo de calendário para receber lembretes.',true);return}try{const permission=await Notification.requestPermission();if(permission==='granted'){localStorage.setItem('ciclo-revisoes-notificar','true');notificationKey='';message('Notificações ativadas enquanto o site estiver aberto.');render()}else message('A permissão de notificações não foi concedida. Os avisos continuam no painel.')}catch{message('Não foi possível ativar as notificações. Os avisos continuam no painel.',true)}};
function icsText(text){return String(text||'').replace(/\\/g,'\\\\').replace(/\n/g,'\\n').replace(/,/g,'\\,').replace(/;/g,'\\;').replace(/\r/g,'')}
$('review-calendar').onclick=()=>{const d=entities(),rows=d.events.filter(r=>r.status==='scheduled'&&(!$('review-filter-subject').value||r.subject===$('review-filter-subject').value));if(!rows.length){message('Não há revisões pendentes para exportar.');return}let lines=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Ciclo de Estudos//Revisoes//PT-BR','CALSCALE:GREGORIAN'];for(const r of rows){const date=r.dueDate.replace(/-/g,''),plan=d.plans.find(p=>p.id===r.planId);lines.push('BEGIN:VEVENT',`UID:${r.id}@ciclo-estudos.local`,`DTSTAMP:${now().replace(/[-:]/g,'').replace(/\.\d{3}/,'')}`,`DTSTART:${date}T090000`,`DTEND:${date}T093000`,`SUMMARY:${icsText('Revisão · '+r.subject+' · '+r.topic)}`,`DESCRIPTION:${icsText('D+'+r.interval+' · '+(plan?.notes||'')+' '+(r.notes||''))}`,'BEGIN:VALARM','ACTION:DISPLAY','TRIGGER:PT0M',`DESCRIPTION:${icsText('Revisar '+r.topic)}`,'END:VALARM','END:VEVENT')}lines.push('END:VCALENDAR');const blob=new Blob([lines.join('\r\n')+'\r\n'],{type:'text/calendar;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='ciclo-revisoes.ics';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);message(`${rows.length} lembrete(s) exportado(s). Importe o arquivo no calendário que você usa.`)};
window.addEventListener('studydatachange',render);window.addEventListener('plannerchange',render);setInterval(()=>updateReminders(entities()),60000);
$('review-plan-date').value=today();render();
})();
