(function(){
'use strict';
const C=window.StudyCore,$=id=>document.getElementById(id),STORE='ciclo-estudos-registros-v2',CONNECTION='ciclo-github-endereco-v1',now=()=>new Date().toISOString(),uuid=()=>crypto.randomUUID();
let saved;try{saved=JSON.parse(localStorage.getItem(STORE))}catch{}
const plannerWasSaved=!!localStorage.getItem(KEY);
let data={schema:2,planner:{value:structuredClone(state),updatedAt:saved?.planner?.updatedAt||(plannerWasSaved?now():'')},sessions:saved?.sessions||[]};
let timer=saved?.timer||{subject:'',startedAt:null,segments:[],mode:'idle'};
let dirty=saved?.dirty||false,editId=null,visibleRows=30,token='',repo='',branch='',connected=false,connecting=false,syncing=false,syncTimer=null,lastSync=saved?.lastSync||'',connectionEpoch=0;
const cleanTimer=()=>({subject:'',startedAt:null,segments:[],mode:'idle'});
function persist(){try{localStorage.setItem(STORE,JSON.stringify({planner:data.planner,sessions:data.sessions,timer,dirty,lastSync}))}catch{showMessage('Não foi possível atualizar a cópia local. Baixe um backup e libere espaço no navegador.',true)}}
function documentData(){return {schema:2,planner:{value:structuredClone(state),updatedAt:data.planner.updatedAt},sessions:structuredClone(data.sessions)}}
function showMessage(text,error=false){$('study-message').textContent=text;$('study-message').hidden=false;$('study-message').classList.toggle('error',error)}
function announce(text,error=false){$('github-status').textContent=text;$('github-status').classList.toggle('error',error);updateChip()}
function updateChip(){const chip=$('sync-chip');chip.textContent=syncing?'Salvando no GitHub…':connected?(dirty?'Alterações pendentes':'Salvo no GitHub'):(dirty?'Pendente · conectar ao GitHub':'Cópia local');chip.classList.toggle('pending',dirty&&!syncing)}
function timestamp(previous){return new Date(Math.max(Date.now(),C.stamp(previous)+1)).toISOString()}
function changed(){dirty=true;persist();updateChip();if(connected){clearTimeout(syncTimer);syncTimer=setTimeout(()=>syncGitHub(),2000)}}
window.addEventListener('plannerchange',()=>{data.planner={value:structuredClone(state),updatedAt:timestamp(data.planner.updatedAt)};changed();fillSubjects()});

function fillSubjects(){let prior=$('timer-subject').value;let subjects=state.subjects.filter(s=>s.name.trim()&&s.status!=='Aguardando').map(s=>s.name);if(timer.subject&&!subjects.includes(timer.subject))subjects.unshift(timer.subject);$('timer-subject').innerHTML=subjects.map(n=>`<option>${esc(n)}</option>`).join('');if(subjects.includes(prior))$('timer-subject').value=prior;if(timer.subject&&timer.mode!=='idle')$('timer-subject').value=timer.subject;$('subject-options').innerHTML=state.subjects.filter(s=>s.name.trim()).map(s=>`<option value="${esc(s.name)}"></option>`).join('')}
function timerMillis(){return timer.segments.reduce((sum,x)=>sum+Math.max(0,x.end-x.start),0)+(timer.startedAt?Math.max(0,Date.now()-timer.startedAt):0)}
function pauseTimer(mode='paused'){if(timer.startedAt){timer.segments.push({start:timer.startedAt,end:Date.now()});timer.startedAt=null}timer.mode=mode;persist();paintTimer()}
function paintTimer(){$('timer-clock').textContent=C.formatClock(timerMillis());$('timer-state').textContent=timer.mode==='running'?'Em andamento · pause nas interrupções':timer.mode==='paused'?'Pausado · o tempo não está contando':timer.mode==='stopped'?'Parado · salve para registrar as horas':'Pronto para iniciar';$('timer-start').disabled=timer.mode==='running'||!$('timer-subject').value;$('timer-start').textContent=timer.mode==='idle'?'Iniciar':'Retomar';$('timer-pause').disabled=timer.mode!=='running';$('timer-stop').disabled=timer.mode==='idle'||timer.mode==='stopped';$('timer-save').disabled=timer.mode==='running'||timerMillis()<1000;$('timer-subject').disabled=timer.mode!=='idle'}
$('timer-start').onclick=()=>{if(timer.mode==='idle')timer.subject=$('timer-subject').value;if(!timer.subject){showMessage('Ative uma matéria no planejamento para usar o cronômetro.',true);return}timer.startedAt=Date.now();timer.mode='running';persist();paintTimer()};
$('timer-pause').onclick=()=>pauseTimer();$('timer-stop').onclick=()=>pauseTimer('stopped');
$('timer-save').onclick=()=>{if(timer.mode==='running'||timerMillis()<1000)return;const group=uuid(),at=now(),parts=C.splitSegments(timer.segments);if(!parts.length){showMessage('A sessão precisa ter pelo menos um segundo.',true);return}for(const part of parts)data.sessions.push({id:uuid(),group,date:part.date,subject:timer.subject,seconds:part.seconds,source:'timer',note:'',createdAt:at,updatedAt:at,deleted:false});timer=cleanTimer();changed();fillSubjects();renderStudies();paintTimer();showMessage(connected?'Sessão registrada. A sincronização com o GitHub ocorrerá em seguida.':'Sessão registrada na cópia local. Conecte ao GitHub para salvá-la lá.')};
setInterval(()=>{if(timer.mode==='running')paintTimer()},500);
document.addEventListener('visibilitychange',()=>{persist();paintTimer()});
window.addEventListener('pagehide',()=>persist());

function activeRecords(){return data.sessions.filter(r=>!r.deleted)}
function shortDate(date){const d=new Date(date+'T12:00:00');return d.toLocaleDateString('pt-BR')}
function renderStudies(){const records=activeRecords(),today=C.dateKey(new Date()),wk=C.bucketKey(today,'weekly'),month=today.slice(0,7);$('done-today').textContent=C.formatHours(records.filter(r=>r.date===today).reduce((n,r)=>n+r.seconds,0));$('done-week').textContent=C.formatHours(records.filter(r=>C.bucketKey(r.date,'weekly')===wk).reduce((n,r)=>n+r.seconds,0));$('done-month').textContent=C.formatHours(records.filter(r=>r.date.startsWith(month)).reduce((n,r)=>n+r.seconds,0));renderChart();renderHistory()}
function bucketLabel(key,mode){return mode==='monthly'?new Date(key+'-01T12:00:00').toLocaleDateString('pt-BR',{month:'short',year:'2-digit'}):shortDate(key).slice(0,5)}
function renderChart(){const mode=$('chart-mode').value,ref=$('chart-date').value;if(!C.validDate(ref))return;const points=C.chartBuckets(data.sessions,mode,ref),maxHours=Math.max(1,...points.map(p=>p.seconds/3600)),ceil=Math.ceil(maxHours),W=Math.max(420,Math.round($('study-chart').clientWidth||960)),H=280,L=48,R=12,T=24,B=70,plotH=H-T-B,plotW=W-L-R,step=plotW/points.length;
let shapes=`<title>Horas líquidas de estudo ${mode==='daily'?'por dia':mode==='weekly'?'por semana':'por mês'}</title>`;
for(let k=0;k<=4;k++){let y=T+plotH-k*plotH/4;shapes+=`<line x1="${L}" y1="${y}" x2="${W-R}" y2="${y}" stroke="#e1eaf0"/><text x="${L-9}" y="${y+5}" text-anchor="end" font-size="14" fill="#596f80">${Number((ceil*k/4).toFixed(1))}h</text>`}
points.forEach((p,i)=>{const height=p.seconds/3600/ceil*plotH,x=L+i*step+step*.16,y=T+plotH-height,width=step*.68,tx=x+width/2,ty=H-40;shapes+=`<rect x="${x}" y="${y}" width="${width}" height="${height}" rx="3" fill="#197eaa"><title>${esc(mode==='weekly'?'Semana de '+shortDate(p.key):mode==='monthly'?p.key:shortDate(p.key))}: ${C.formatHours(p.seconds)}</title></rect><text x="${tx}" y="${ty}" ${W<700?`transform="rotate(-35 ${tx} ${ty})"`:''} text-anchor="middle" font-size="14" fill="#506b7f">${esc(bucketLabel(p.key,mode))}</text>`});
$('study-chart').innerHTML=`<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="Gráfico de horas líquidas. Os valores estão disponíveis abaixo.">${shapes}</svg>${points.every(p=>!p.seconds)?'<p class="chart-empty">Nenhum estudo registrado neste período. Use o cronômetro ou adicione um registro manual.</p>':''}`;
$('chart-values').innerHTML=`<table><tbody>${points.map(p=>`<tr><td>${esc(mode==='weekly'?'Semana de '+shortDate(p.key):mode==='monthly'?p.key:shortDate(p.key))}</td><td>${C.formatHours(p.seconds)}</td></tr>`).join('')}</tbody></table>`}
function renderHistory(){const records=activeRecords().filter(r=>$('history-all').checked||r.date.startsWith($('history-month').value)).sort((a,b)=>b.date.localeCompare(a.date)||C.stamp(b.createdAt)-C.stamp(a.createdAt));$('history-body').innerHTML=records.slice(0,visibleRows).map(r=>`<tr><td>${shortDate(r.date)}</td><td>${esc(r.subject)}</td><td>${C.formatHours(r.seconds)}</td><td>${r.source==='timer'?'Cronômetro':'Manual'}</td><td>${esc(r.note||'')}</td><td><button type="button" data-edit="${esc(r.id)}">Editar</button><button type="button" class="delete" data-delete="${esc(r.id)}">Excluir</button></td></tr>`).join('')||'<tr><td colspan="6">Nenhum registro neste período.</td></tr>';$('history-total').textContent=`${records.length} sessão(ões) · ${C.formatHours(records.reduce((a,r)=>a+r.seconds,0))} de estudo líquido`;$('history-more').hidden=records.length<=visibleRows}
function cancelEdit(){editId=null;$('record-heading').textContent='Registrar horas manualmente';$('record-submit').textContent='Salvar registro';$('record-cancel').hidden=true;$('record-form').reset();$('record-date').value=C.dateKey(new Date())}
$('record-form').onsubmit=e=>{e.preventDefault();const date=$('record-date').value,subject=$('record-subject').value.trim(),seconds=C.parseDuration($('record-duration').value);if(!C.validDate(date)||!subject||!seconds){showMessage('Preencha a data, a matéria e uma duração entre 0:01 e 24:00, no formato h:mm.',true);return}const old=data.sessions.find(r=>r.id===editId),at=timestamp(old?.updatedAt);const record={...(old||{}),id:old?.id||uuid(),date,subject,seconds,source:old?.source||'manual',note:$('record-note').value.trim(),createdAt:old?.createdAt||at,updatedAt:at,deleted:false};data.sessions=data.sessions.filter(r=>r.id!==record.id);data.sessions.push(record);changed();cancelEdit();renderStudies();showMessage('Registro salvo. Os totais e gráficos foram recalculados.')};
$('record-cancel').onclick=cancelEdit;
$('history-body').onclick=e=>{const button=e.target.closest('button');if(!button)return;const id=button.dataset.edit||button.dataset.delete,record=data.sessions.find(r=>r.id===id);if(!record)return;if(button.dataset.delete){if(!window.confirm(`Excluir a sessão de ${record.subject} em ${shortDate(record.date)}?`))return;record.deleted=true;record.updatedAt=timestamp(record.updatedAt);if(editId===id)cancelEdit();changed();renderStudies();return}editId=id;$('record-heading').textContent='Editar sessão';$('record-submit').textContent='Salvar alteração';$('record-cancel').hidden=false;$('record-date').value=record.date;$('record-subject').value=record.subject;$('record-duration').value=C.formatHours(record.seconds);$('record-note').value=record.note||'';$('record-form').scrollIntoView({behavior:'smooth',block:'center'})};
$('history-more').onclick=()=>{visibleRows+=30;renderHistory()};
for(const id of ['history-month','history-all'])$(id).onchange=()=>{visibleRows=30;renderHistory()};
for(const id of ['chart-mode','chart-date'])$(id).onchange=renderChart;
window.addEventListener('resize',()=>renderChart());

function encode(text){const bytes=new TextEncoder().encode(text);let str='';for(let i=0;i<bytes.length;i+=8192)str+=String.fromCharCode(...bytes.subarray(i,i+8192));return btoa(str)}
function decode(text){const raw=atob(text.replace(/\s/g,'')),bytes=Uint8Array.from(raw,c=>c.charCodeAt(0));return new TextDecoder().decode(bytes)}
const filePath='ciclo-estudos/dados.json';
function apiUrl(path=''){return `https://api.github.com/repos/${repo.split('/').map(encodeURIComponent).join('/')}${path}`}
async function request(url,options={}){let response;try{response=await fetch(url,{...options,headers:{Accept:'application/vnd.github+json',Authorization:`Bearer ${token}`,'X-GitHub-Api-Version':'2022-11-28',...(options.body?{'Content-Type':'application/json'}:{}),...options.headers},signal:AbortSignal.timeout(20000),cache:'no-store'})}catch{throw new Error('Não foi possível alcançar o GitHub. A cópia local foi mantida; tente sincronizar novamente.') }return response}
async function errorFor(response){let body;try{body=await response.json()}catch{}if(response.status===401)return 'O token é inválido ou expirou. Gere outro e conecte novamente.';if(response.status===403)return 'O GitHub recusou a gravação. Verifique a permissão Contents: Read and write e o acesso ao repositório.';if(response.status===404)return 'O repositório ou a branch não foi encontrado. Confira o nome e o acesso do token.';if(response.status===429)return 'O GitHub limitou as requisições. Aguarde um pouco e tente novamente.';return `O GitHub não concluiu a operação (erro ${response.status}). ${body?.message?.includes('protected')?'A branch está protegida contra gravações diretas.':''}`}
async function readRemote(){const res=await request(apiUrl(`/contents/${filePath}?ref=${encodeURIComponent(branch)}`));if(res.status===404)return {doc:null,sha:null};if(!res.ok)throw new Error(await errorFor(res));const f=await res.json();if(f.encoding!=='base64'||typeof f.content!=='string')throw new Error('O arquivo de dados não pode ser lido neste formato. A cópia local foi mantida.');let doc;try{doc=C.validate(JSON.parse(decode(f.content)))}catch{throw new Error('O arquivo do GitHub contém dados incompatíveis. Ele não foi sobrescrito; seus registros locais foram mantidos.')}return {doc,sha:f.sha}}
function adopt(doc){C.validate(doc);data=doc;state=structuredClone(doc.planner.value);localStorage.setItem(KEY,JSON.stringify(state));persist();for(const id of ['daily','cap','days','perday'])$(id).value=state[id];updateSliderLabels();renderSubjects();renderSchedule();fillSubjects();paintTimer();renderStudies()}
async function syncGitHub(){if(!connected||syncing)return;clearTimeout(syncTimer);syncing=true;updateChip();$('github-sync').disabled=true;const epoch=connectionEpoch;let message='';try{
 for(let attempt=0;attempt<3;attempt++){
  const remote=await readRemote();if(epoch!==connectionEpoch)return;
  const local=documentData(),merged=remote.doc?C.merge(local,remote.doc):C.merge(local,local);
  if(JSON.stringify(remote.doc)===JSON.stringify(merged)){adopt(merged);dirty=false;lastSync=now();persist();message='Dados recuperados. Nenhuma gravação nova foi necessária.';break}
  const serialized=JSON.stringify(merged,null,2);if(new TextEncoder().encode(serialized).length>950000)throw new Error('O histórico chegou ao limite deste arquivo. Baixe um backup antes de continuar.');
  const body={message:`Atualiza estudo e planejamento · ${new Date().toLocaleDateString('pt-BR')}`,content:encode(serialized),branch,...(remote.sha?{sha:remote.sha}:{})};
  const response=await request(apiUrl(`/contents/${filePath}`),{method:'PUT',body:JSON.stringify(body)});
  if(epoch!==connectionEpoch)return;
  if(response.status===409||response.status===422&&remote.sha){if(attempt===2)throw new Error('O arquivo mudou em outra sessão. Nenhum registro local foi perdido; sincronize novamente.');continue}
  if(!response.ok)throw new Error(await errorFor(response));
  // Edits may happen while the request is in flight. Merge them and keep them pending.
  const latest=documentData(),after=C.merge(latest,merged),pending=JSON.stringify(after)!==JSON.stringify(merged);
  adopt(after);dirty=pending;lastSync=now();persist();message=pending?'Gravação concluída. Há novas alterações para sincronizar.':`Salvo no GitHub às ${new Date(lastSync).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}.`;break;
 }
 if(message)announce(message);
 }catch(e){dirty=true;persist();announce(e.message||'A sincronização falhou. Seus registros locais foram mantidos.',true)}finally{syncing=false;$('github-sync').disabled=!connected;updateChip();if(dirty&&connected&&message){syncTimer=setTimeout(()=>syncGitHub(),2000)}}}
$('github-form').onsubmit=async e=>{e.preventDefault();if(connecting||syncing)return;const input=$('github-repo').value.trim();if(!/^[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+$/.test(input)){announce('Use o formato usuário/repositório.',true);return}const value=$('github-token').value.trim();if(!value)return;connecting=true;connected=false;token=value;repo=input;branch=$('github-branch').value.trim();connectionEpoch++;$('github-token').value='';$('github-connect').disabled=true;announce('Verificando acesso ao repositório…');try{const result=await request(apiUrl());if(!result.ok)throw new Error(await errorFor(result));const meta=await result.json();branch=branch||meta.default_branch;if(!branch)throw new Error('O repositório precisa de uma branch. Crie-o com um README e tente novamente.');localStorage.setItem(CONNECTION,JSON.stringify({repo,branch}));connected=true;$('github-disconnect').disabled=false;$('github-branch').value=branch;if(!meta.private)announce('Conectado a um repositório público: os dados gravados nele serão públicos.');await syncGitHub()}catch(e){token='';connected=false;announce(e.message,true)}finally{connecting=false;$('github-connect').disabled=false;updateChip()}};
$('github-sync').onclick=()=>syncGitHub();
$('github-disconnect').onclick=()=>{if(syncing){announce('Aguarde a gravação atual terminar para desconectar.');return}connectionEpoch++;connected=false;token='';clearTimeout(syncTimer);$('github-sync').disabled=true;$('github-disconnect').disabled=true;announce('Desconectado. O histórico permanece na cópia local; o token foi removido da memória.')};
window.addEventListener('online',()=>{if(connected)syncGitHub()});
window.addEventListener('focus',()=>{if(connected&&!syncing)syncGitHub()});
$('backup-export').onclick=()=>{const blob=new Blob([JSON.stringify(documentData(),null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`ciclo-estudos-${C.dateKey(new Date())}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
$('backup-import').onchange=async e=>{const file=e.target.files?.[0];if(!file)return;try{if(file.size>1000000)throw new Error('O backup excede o tamanho permitido.');const imported=C.validate(JSON.parse(await file.text())),merged=C.merge(documentData(),imported);adopt(merged);changed();announce('Backup importado e combinado com os registros existentes. Conecte ao GitHub para sincronizar.')}catch(error){announce(error.message||'Não foi possível importar este arquivo.',true)}finally{e.target.value=''}};
document.querySelectorAll('[data-view]').forEach(button=>{button.onclick=()=>{document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-selected',String(b===button)));for(const id of ['planner-view','study-view','github-view'])$(id).hidden=id!==button.dataset.view;if(button.dataset.view==='study-view'){fillSubjects();paintTimer();renderStudies()}}});
const today=C.dateKey(new Date());$('record-date').value=today;$('chart-date').value=today;$('history-month').value=today.slice(0,7);
try{const config=JSON.parse(localStorage.getItem(CONNECTION));if(config){$('github-repo').value=config.repo;$('github-branch').value=config.branch}}catch{}
persist();fillSubjects();paintTimer();renderStudies();updateChip();
})();
